homeassistant:
  name: Home
  latitude: !secret latitude 
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: imperial
  time_zone: America/Los_Angeles
  customize: !include customize.yaml
  customize_glob:
    "*sourcenodeid":
      hidden: true
    "*motion*":
      device_class: motion
      
frontend:
  themes: !include_dir_merge_named themes/
  javascript_version: es5

# Enables configuration UI
config:

alexa:

intent_script:
  ActivateSceneIntent:
    action:
      service: scene.turn_on
      data_template:
        entity_id: scene.{{ Scene | replace(" ", "_") }}
    speech:
      type: plain
      text: !include alexa_confirm.yaml

  ActivateScriptIntent:
    action:
      service: script.turn_on
      data_template:
        entity_id: script.{{ Script | replace(" ", "_") }}
    speech:
      type: plain
      text: !include alexa_confirm.yaml

  amzn1.ask.skill.eaf2305c-434e-4b9f-b311-f8b0093323b0:
    action:
      service: script.bye_felicia
    speech:
      type: plain
      text: "Later Hater"

input_boolean:
  night_mode:
    name: Night Mode
    initial: off
    icon: mdi:weather-night
  vacation_mode:
    name: Vacation Mode
    initial: off
    icon: mdi:airplane

http:
  api_password: !secret http_password
  ip_ban_enabled: True
  login_attempts_threshold: 3
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  include_used_components: true

# Discover some devices automatically
discovery:
        
remote:
  - platform: harmony
    name: Harmony Hub
    activity: Watch TV

ring:
  username: !secret ring_username
  password: !secret ring_password

telegram_bot:
  - platform: polling
    api_key: !secret telegram_api
    allowed_chat_ids:
      - !secret telegram_chat_id1

notify:
  - name: tgnotify
    platform: telegram
    chat_id: !secret telegram_chat_id1

# Enables support for tracking state changes over time
history:
  exclude:
    entities:
      - sensor.pws_weather_1d
      - sensor.pws_weather_1n
      - sensor.pws_weather_2d
      - sensor.pws_weather_2n
      - sensor.pws_weather_3d
      - sensor.pws_weather_high_1d_f
      - sensor.pws_weather_low_1d_f
      - sensor.pws_weather_wind_degrees
      - sensor.pws_weather_3n
      - sensor.pws_weather_precip_1d_in
      - sensor.pws_weather_precip_today_in
      - sensor.pws_weather_pressure_trend
      - sensor.ssl_cert_expiry
#     - sensor.google_wifi_status
      - sensor.google_wifi_new_version
      - sensor.google_wifi_uptime
      - sensor.google_wifi_last_restart
      - sensor.google_wifi_local_ip
      - sensor.swap_use
      - sensor.ram_use
      - sensor.disk_use_
      - sensor.average_load_1m
      - sensor.average_load_15m
      - sensor.ipv4_address_enxb827ebb89b75
      - sensor.since_last_boot
    domains:
      - sensor
      - group
      - zwave
      - automation
      - scene
  include:
    entities:
      - sensor.front_door_lock_status
      - sensor.front_door_lock_alarm_type
    domains:
      - alarm_control_panel
      - binary_sensor
      - light
      - switch
      - input_boolean
 
recorder:
  db_url: !secret dburl
  purge_interval: 1
  purge_keep_days: 5
  exclude:
    entities:
      - sensor.google_wifi_new_version
      - sensor.google_wifi_uptime
      - sensor.google_wifi_last_restart
      - sensor.google_wifi_local_ip
      - sensor.swap_use
      - sensor.ram_use
      - sensor.disk_use_
      - sensor.average_load_1m
      - sensor.average_load_15m
      - sensor.ipv4_address_enxb827ebb89b75
      - sensor.since_last_boot
    domains:
      - group 

# View all events in a logbook
logbook:
  exclude:
    domains:
      - zwave
      - sensor
      - climate
      - group
  include:
    domains:
      - binary_sensor
      - alarm_control_panel
      - light
      - switch
      - automation

  # Track the sun
sun:

zwave:
  usb_path: /dev/zwave
  network_key: !secret zwave_network_key 
  device_config: !include zwave_device_config.yaml

binary_sensor:
  - platform: ring
    monitored_conditions:
      - ding
      - motion
  - platform: template
    sensors:
      front_door_open:
        friendly_name: 'Front Door Security'
        value_template: '{{ is_state("sensor.front_door_closed_access_control", "22") }}'
        entity_id: sensor.front_door_closed_access_control
        device_class: opening
      back_door_open:
        friendly_name: 'Back Door Security'
        value_template: '{{ is_state("sensor.back_door_access_control", "22") }}'
        entity_id: sensor.back_door_access_control
        device_class: opening
      garage_open:
        friendly_name: 'Garage Security'
        value_template: '{{ is_state("sensor.garage_access_control", "22") }}'
        entity_id: sensor.garage_access_control
        device_class: opening


sensor:
#  - platform: yr
  - platform: google_wifi
    monitored_conditions:
      - uptime
      - status
  - platform: systemmonitor
    resources:
    - type: disk_use_percent
      arg: /
    - type: memory_use_percent
#   - type: swap_use_percent
    - type: load_1m
    - type: load_15m
#   - type: ipv4_address
#     arg: enxb827ebb89b75
    - type: since_last_boot
  - platform: wunderground
    api_key: !secret wunderground_api
    pws_id: !secret wu_pws 
    monitored_conditions:
      - dewpoint_f
      - feelslike_f
      - precip_today_in
      - pressure_in
      - temp_f
      - temp_high_1d_f
      - temp_low_1d_f
      - wind_degrees
      - wind_mph
      - weather_1d
      - weather_1n
      - weather_2d
      - weather_2n
      - weather_3d
      - weather_3n
  - platform: ring
    monitored_conditions:
      - battery
      - last_ding
      - last_motion
  - platform: command_line
    name: SSL Cert Expiry
    unit_of_measurement: days
    scan_interval: 10800
    command: "ssl-cert-check -b -c /etc/letsencrypt/live/4445h.duckdns.org/cert.pem | awk '{ print $NF }'"
  - platform: template
    sensors:
      lock_front_door_battery:
        friendly_name: 'Lock Battery'
        value_template: '{{ states.zwave.front_door_lock.attributes.battery_level }}'
        unit_of_measurement: '%'
        entity_id: zwave.front_door_lock
      lock_front_door_status: 
        friendly_name: 'Lock Status'
        value_template: '{{ states.lock.front_door_lock_locked.attributes.lock_status }}'
        entity_id: lock.front_door_lock_locked

emulated_hue:
  expose_by_default: false
#  exposed_domains:
#    - light
#    - switch
#    - scene

#switch:
# - platform: tplink
#   host: 192.168.86.112
# - platform: tplink
#   host: 192.168.86.150
#   name: 'Holiday Tree'

ecobee:
  api_key: !secret ecobee_api_key

alarm_control_panel:
  - platform: manual
    name: "House Alarm"
    pending_time: 60
    armed_home:
      pending_time: 0
    armed_away:
      pending_time: 20
    triggered:
      pending_time: 0

# Text to speech
#tts:
#  - platform: google

group: !include groups.yaml
automation: !include_dir_merge_list automations/
script: !include scripts.yaml
scene: !include scenes.yaml
