- alias: 'Hallway motion'
  id: 'hallway_motion'
  initial_state: true
  trigger:
    platform: state
    entity_id: 
      - binary_sensor.hallway_motion_sensor
      - binary_sensor.hallway_rear_motion_sensor
    to: 'on'
  action:
    service: light.turn_on
    data_template:
      entity_id: light.upstairs_hall_level
      brightness_pct: >
        {% if is_state("input_boolean.night_mode", "on") -%}
        10
        {%- else -%}
        100
        {%- endif %}

- alias: 'Hallway motion over'
  id: 'hallway_motion_over'
  initial_state: true
  trigger:
    platform: state
    entity_id:
      - binary_sensor.hallway_motion_sensor
      - binary_sensor.hallway_rear_motion_sensor
    to: 'off'
    for: 
      minutes: 1
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: binary_sensor.hallway_motion_sensor
        state: 'off'
      - condition: state
        entity_id: binary_sensor.hallway_rear_motion_sensor
        state: 'off'
  action:
    service: light.turn_off
    entity_id: light.upstairs_hall_level

- alias: 'Bathroom motion'
  id: 'bathroom_motion'
  initial_state: true
  trigger:
    platform: state
    entity_id: binary_sensor.bathroom_motion_sensor
    to: 'on'
  action:
    service: light.turn_on
    data_template:
      entity_id: light.master_bathroom_level
      brightness_pct: >
        {% if is_state("input_boolean.night_mode", "on") -%}
        5
        {%- else -%}
        100
        {%- endif %}

- alias: 'Bathroom motion over'
  id: 'bathroom_motion_over'
  initial_state: true
  trigger:
    platform: state
    entity_id: binary_sensor.bathroom_motion_sensor
    to: 'off'
    for:
      minutes: 5
  action:
    service: light.turn_off
    entity_id: light.master_bathroom_level

