
- alias: 'Set dark theme at night'
  id: 'set_dark_theme'
  initial_state: true
  trigger:
    - platform: sun
      event: sunset
  action:
    - service: frontend.set_theme
      data:
        name: 'dark_theme'

- alias: 'Set light theme at sunrise'
  id: 'set_light_theme'
  initial_state: true
  trigger:
    - platform: sun
      event: sunrise
  action:
    - service: frontend.set_theme
      data:
        name: 'default'

