- alias: 'Exterior on 30 min before sunset'
  id: '1504752058793'
  trigger:
  - event: sunset
    platform: sun
    offset: -00:30
  action:
    entity_id: 
      - switch.exterior_switch
      - switch.holiday_lights
    service: switch.turn_on

- alias: 'Sunset interior lights'
  id: '1504752058794'
  trigger:
  - event: sunset
    platform: sun
  action:
    entity_id: scene.sunset
    service: scene.turn_on   

- alias: 'Holiday lights off'
  id: '7890'
  trigger:
    platform: time
    at: '23:00:00'
  action:
    entity_id: switch.holiday_lights
    service: switch.turn_off

- alias: 'Exterior stay on at night'
  id: '1234'
  trigger:
    platform: state
    entity_id: switch.exterior_switch
    to: 'off'
    for:
      minutes: 7
  condition:  
    condition: template
    value_template: '{{ states.sun.sun.state == "below_horizon" }}'
  action:
    service: switch.turn_on
    entity_id: switch.exterior_switch

- alias: 'Front door open night - lights on'
  id: '1235'
  trigger:
    platform: state
    entity_id: binary_sensor.front_door_security
    to: 'Open'
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: '{{ states.sun.sun.state == "below_horizon" }}'
      - condition: state
        entity_id: input_boolean.vacation_mode
        state: 'false'
  action:
    service: scene.turn_on
    entity_id: scene.kitchen_dim
        
- alias: 'Late night lights off, weekday'
  id: '1236'
  trigger:
    platform: time
    at: '02:00:00'
  condition:
    condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
    service: homeassistant.turn_off
    entity_id:
      - light.living_room_level
      - light.dining_room_level
      - light.front_bathroom_level
      - light.main_kitchen_light_level
      - light.kitchen_spots_level
      - light.front_hall_level
      - light.tv_room_ceiling_level
      - light.hue_white_right
      - light.hue_white_left
      - light.stairs_level
      - light.upstairs_hall_level
      - light.office_level
      - switch.front_hall_switch
      - switch.holiday_lights

- alias: 'Vacation mode lights off'
  id: 'vacation_lights_off'
  trigger:
    platform: time
    at: '23:00:00'
  condition:
    condition: state
    entity_id: input_boolean.vacation_mode
    state: 'on'
  action:
    service: scene.turn_on
    entity_id: scene.goodnight

- alias: 'Sunrise exterior off'
  id: '1504752058792'
  trigger:
  - event: sunrise
    platform: sun
  action:
    service: homeassistant.turn_off
    entity_id: 
      - switch.exterior_switch
      - input_boolean.night_mode

